=== OCFL/spec/draft/spec/inventory_schema.json
{
    "$id": "https://ocfl.io/0.1/spec/inventory_schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "JSON Schema for OCFL Inventory files",
    "description": "Note that this schema does not permit extension keys, only keys defined in the OCFL Specification are admitted.",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "digestAlgorithm": {
            "enum": [ "sha256", "sha512" ]
        },
        "fixity": {
            "description": "Optional property. Keys are digest type and values are objects with digest to file mappings",
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^(md5|sha1|sha256|sha512|blake2b-512)$": {
                    "$ref": "#/definitions/digests_to_files"
                }
            }
        },
        "head": {
            "$ref": "#/definitions/version_directory"
        },
        "id": {
            "type": "string",
            "pattern": ".+"
        },
        "manifest": {
            "$ref": "#/definitions/digests_to_files"
        },
        "type": {
            "description": "Seems that using `const` would be nicer but that doesn't seem to work with Python jsonschema",
            "enum": ["https://ocfl.io/1.0/spec/#inventory"]
        },
        "versions": {
            "description": "Each key is a version directory name with version objects as values",
            "type" : "object",
            "additionalProperties": false,
            "patternProperties": {
                "^v\\d+$": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "created": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "message": {
                            "type": "string"
                        },
                        "state": {
                            "$ref": "#/definitions/digests_to_files"
                        },
                        "user": {
                            "type": "object",
                            "additionalProperties": false,
                            "properties": {
                                "address": {
                                    "type": "string",
                                    "pattern": ".+"
                                },
                                "name": {
                                    "type": "string",
                                    "pattern": ".+"
                                }
                            },
                            "required": [ "name" ]
                        }
                    },
                    "required": [ "created", "state" ]
                }
            }
        },
        "contentDirectory": {
            "type": "string",
            "pattern": "^[^/]+$"
        }
    },
    "required": [ "digestAlgorithm", "head", "id", "manifest", "type", "versions" ],
    "definitions": {
        "digests_to_files": {
            "description": "Object pattern used for `manifest`, `state` and within `fixity` objects. Keys are digests which MUST be hex strings with chars 0-9, a-f or A-F, values are arrays of file paths (non-empty strings). This pattern permits digests that are 32, 40, 64, or 128 hex digits long (matching md5, sha1, sha256, and sha512 / blake2b-512 respectively) but does not check that the length is correct for the type",
            "type" : "object",
            "additionalProperties": false,
            "patternProperties": {
                "^([\\da-fA-F]{32}|[\\da-fA-F]{40}|[\\da-fA-F]{64}|[\\da-fA-F]{128})$": {
                    "type": "array",
                    "uniqueItems": true,
                    "items": {
                        "type": "string",
                        "pattern": ".+"
                    }
                }
            }
        },
        "version_directory": {
            "description": "String pattern to match allowed version directory names",
            "type": "string",
            "pattern": "^v\\d+$"
        }
    }
}

=== OCFL/spec/history/inventory.json
{
  "digestAlgorithm": "sha512",
  "head": "v1",
  "id": "https://ocfl.io/history",
  "manifest": {
    "77d6ecdbc24ad892361616e2dddca97ef7c281795969d2114338ea35546da809c5af55f2ed43bfb00f78fdb80fe276c530d503d44592fdc9d4b26c6b05246bc9": [
      "v1/content/Oxford Common Filesystem Layout--Initial Proposal.pdf"
    ],
    "a014a467dc3b03bef8ffc94410552e151607a966c7b65453296777e559c5c670808439afb38eb751d22b2a74cf075e88a16c6e9281b4f20e08d869d80b757283": [
      "v1/content/README.md"
    ],
    "ab892c47ba5209238973b04ebed296fe587dbed056c450b9c8653933899ca66fd6292995c355bde943795f82e1fe3827d9351e699092917f1bfbe8840362396b": [
      "v1/content/Oxford Common Filesystem Layout - Discussion Paper - 2018-01-22.pdf"
    ]
  },
  "type": "https://ocfl.io/1.0/spec/#inventory",
  "versions": {
    "v1": {
      "created": "2020-07-30T11:59:52.277818Z",
      "message": "Added copy of the initial OCFL documents and a README.",
      "user": {
        "name": "Andrew Hankinson",
        "address": "https://orcid.org/0000-0003-2663-0003"
      },
      "state": {
        "77d6ecdbc24ad892361616e2dddca97ef7c281795969d2114338ea35546da809c5af55f2ed43bfb00f78fdb80fe276c530d503d44592fdc9d4b26c6b05246bc9": [
          "Oxford Common Filesystem Layout--Initial Proposal.pdf"
        ],
        "a014a467dc3b03bef8ffc94410552e151607a966c7b65453296777e559c5c670808439afb38eb751d22b2a74cf075e88a16c6e9281b4f20e08d869d80b757283": [
          "README.md"
        ],
        "ab892c47ba5209238973b04ebed296fe587dbed056c450b9c8653933899ca66fd6292995c355bde943795f82e1fe3827d9351e699092917f1bfbe8840362396b": [
          "Oxford Common Filesystem Layout - Discussion Paper - 2018-01-22.pdf"
        ]
      }
    }
  }
}
